### ISSUE TITLE
Add a waggle plugin for the MRR

### ISSUE THREAD

**Issue by jrobrien91** [CROCUS-Urban/measurement-strategy#12]
### What instrument do you want a plugin for?

The Micro Rain Radar MRR at 24 GHz is a unique meteorological radar profiler for Doppler spectra of hydrometeors in height ranges 15 m … 6000 m. The high resolution in time and height enables the MRR to monitor the genesis of frozen hydrometeors, the melting zone (bright band) and the formation of rain drops. With the derived rain rate the MRR offers a calibration of weather radar.

### When do you need this plugin written by?

I need this by July 2023!

**Comment by mgrover1** [comment]
@rcjackson created + is testing the repo here https://github.com/rcjackson/plugin-mrrpro
