### ISSUE TITLE
Add a waggle plugin for the AQT530

### ISSUE THREAD

**Issue by mgrover1** [CROCUS-Urban/measurement-strategy#7]
### What instrument do you want a plugin for?

The AQT530 instrument, which measures air quality

### When do you need this plugin written by?

I need this by May 2023

[Link to plugin](https://github.com/jrobrien91/waggle-aqt)

**Comment by jrobrien91** [comment]
@mgrover1 you can assign this to me as well

**Comment by mgrover1** [comment]
Done 😄

**Comment by mgrover1** [comment]
Is it in progress?

**Comment by jrobrien91** [comment]
Plan to start today!

**Comment by mgrover1** [comment]
Closing this @jrobrien91 now that it is good to go!

https://github.com/jrobrien91/waggle-aqt
